workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - build
  - test
#  - compliance


#TODO: enable when clang format file has been added
.formatting:
  stage: compliance
  needs: []
  image: ubuntu:24.04
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y --no-install-recommends git clang-format
  script:
    - git clang-format --verbose --diff ${CI_MERGE_REQUEST_DIFF_BASE_SHA}


.debian-based:
  parallel:
    matrix:
       - MPI: [ mpich, openmpi ]
  needs: []
  variables:
    CMAKE_BUILD_TYPE: Debug
    OMPI_ALLOW_RUN_AS_ROOT: "1"
    OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
    OMPI_MCA_mpi_yield_when_idle: "1"
    OMPI_MCA_rmaps_base_oversubscribe: "1"
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - >-
      apt-get install -y --no-install-recommends
      gcc
      g++
      gfortran 
      cmake 
      make
      libopenmpi-dev
      libmpich-dev
      git
      python3
      libxml2-dev
      libomp-dev
      llvm-14-tools
    - |
      if [[ "${USE_CLANG}" == "1" ]]; then
        apt-get install -y --no-install-recommends clang
        export MPICH_CC=clang MPICH_CXX=clang++
        export OMPI_CC=clang OMPI_CXX=clang++
      else
        export MPICH_CC=gcc MPICH_CXX=g++
        export OMPI_CC=gcc OMPI_CXX=g++
      fi
  script:
    - export PATH=$PATH:/usr/lib/llvm-14/bin
    - export FI_PROVIDER=shm MPIR_CVAR_POLLS_BEFORE_YIELD=1
    - export OMPI_MCA_btl=vader,self OMPI_MCA_mpi_yield_when_idle=1
    - >-
      cmake -S ./ -B build -DCMAKE_C_COMPILER=mpicc.${MPI} \
                           -DCMAKE_CXX_COMPILER=mpicxx.${MPI} \
                           -DMPIEXEC_EXECUTABLE=${MPIEXEC} \
                           -DOTFCPT_TEST_LB=.8 \
                           -DOTFCPT_TEST_UB=1.05 \
                           -DOTFCPT_TEST_WORK=300000
    - cmake --build build
    - cmake --install build
    - EXIT_CODE=0
    - cmake --build build -- check || EXIT_CODE=$?
    - ldd build/libOTFCPT.so | grep -q "libstdc++" && echo -e "\e[1;31mFound libstdc++ dependency, failure\e[0m" && exit 1
    - exit $EXIT_CODE
  artifacts:
    reports:
      junit: build/tests/check.xunit.xml

ubuntu:
  stage: test
  image: ubuntu:24.04
  extends: .debian-based
  variables:
    MPIEXEC: mpiexec.openmpi # TODO: Change to ${MPI} when Ubuntu's mpich hydra launcher is fixed
    LDFLAGS: "-flto=auto"
  parallel:
    matrix:
      - USE_CLANG: ["0", "1"]

debian:
  stage: test
  image: debian:12
  extends: .debian-based
  variables:
    MPIEXEC: mpiexec.${MPI} # TODO: Change to ${MPI} when Debian's mpich hydra launcher is fixed
  parallel:
    matrix:
      - USE_CLANG: ["0", "1"]

.cluster-template:
    tags: 
      - "downscope-testing"
    variables:
      SLURM_PARAM_CPUS_PER_TASK: "-c 4"
      SLURM_PARAM_ACCOUNT: "-A rwth1282" 
      SLURM_PARAM_PARTITION: "-p c23ms" 
      SLURM_DPARAM_ACCOUNT: "-A rwth1282" 
      SLURM_DPARAM_PARTITION: "-p c23ms" 
    before_script:
      - module purge
      - module load "${TOOLCHAIN}/${VERSION}"
      - >-
        if [[ "${COMPILER}" == *"Clang"* ]]; then
          module load Clang
          export CC=clang CXX=clang++
          export OMPI_CC=clang OMPI_CXX=clang++
          export MPICH_CC=clang MPICH_CXX=clang++
        fi
      - >-
        if [[ "${USE_ONEAPI}" == "1" ]]; then
          export CC=icx CXX=icpx
          export I_MPI_CC=icx I_MPI_CXX=icpx
        fi
      - export I_MPI_FABRICS=shm I_MPI_WAIT_MODE=1
      - export OMPI_MCA_btl=vader,self OMPI_MCA_mpi_yield_when_idle=1
    parallel:
      matrix:
        - TOOLCHAIN: ["iimpi"]
          VERSION: ["2022a", "2022b", "2023a", "2023b"]
          COMPILER: [""]
          USE_ONEAPI: ["0", "1"]
        - TOOLCHAIN: ["iimpi"]
          VERSION: ["2024a", "2025a"] # These versions do not include the legacy compilers
          COMPILER: [""]
          USE_ONEAPI: ["1"]
        - TOOLCHAIN: ["iimpi"]
          VERSION: ["2022a", "2023a", "2023b", "2024a", "2025a"]
          COMPILER: ["Clang"]
        - TOOLCHAIN: ["gompi"]
          VERSION: ["2022a", "2023a", "2023b", "2024a", "2025a"]
          COMPILER: ["Clang", ""]

.cluster-build:
    stage: build
    extends: .cluster-template
    script:
      - mkdir build
      - cmake -S ./ -B build -DCMAKE_INSTALL_PREFIX=$PWD/install -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - cmake --build build --parallel ${SLURM_CPUS_PER_TASK}
      - cmake --install build

cluster:
    stage: test
    extends: .cluster-template
    script:
      - !reference [.cluster-build, script]
      - EXIT_CODE=0
      - cmake --build build -- check || EXIT_CODE=$?
      - ldd build/libOTFCPT.so | grep -q "libstdc++" && echo -e "\e[1;31mFound libstdc++ dependency, failure\e[0m" && exit 1
    artifacts:
      reports:
        junit: build/tests/check.xunit.xml
