sed -e 's/\(\.\|->\|(\|*\|&\| \)Assign(/\1assign(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Append(/\1append(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Back(/\1back(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Capacity(/\1capacity(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Clear(/\1clear(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Data(/\1data(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Empty(/\1empty(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)EnsureSize(/\1ensure_size(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Erase(/\1erase(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Find(/\1find(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Insert(/\1insert(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Length(/\1length(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)PopBack(/\1pop_back(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)PushBack(/\1push_back(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Raw(/\1raw(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Reserve(/\1reserve(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Resize(/\1resize(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Size(/\1size(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Substr(/\1substr(/g' \
    -e 's/\(\.\|->\|(\|*\|&\| \)Swap(/\1swap(/g' \
    -i $@
#    -e 's/\(\.\|->\|(\|*\|&\| \)Reset(/\1reset(/g' \
